platzipremiosapp/platzipremiosapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls"))
]

platzipremiosapp/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/detail/", views.DetailView.as_view(), name="details"),
    path("<int:pk>/results/", views.ResultView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),


]

platzipremiosapp/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

platzipremiosapp/polls/views.py
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question, Choice


""" def index(request):
    lastest_questions_list = Question.objects.all()
    return render(request, "polls/index.html", {
        "lastest_questions_list": lastest_questions_list,
    })


def details(request, question_id):
    question = get_list_or_404(Question, pk=question_id)
    return render(request, "polls/details.html", {
        "question": question[0],
    })


def results(request, question_id):
    question = get_list_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {
        "question": question[0]
    }) """
    


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "lastest_questions_list"
    def get_queryset(self):
        """Return the lastest five published questions"""
        return Question.objects.order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name='polls/details.html'

class ResultView(generic.DetailView):
    model = Question
    template_name='polls/results.html'

def vote(request, question_id):
    question = get_list_or_404(Question, pk=question_id)
    question = question[0]
    try:
        select_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/details.html", {
            "question": question,
            "error_message": "No has seleccionado una opción"
        })
    else:
        select_choice.votes += 1
        select_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

platzipremiosapp/polls/templates/polls/details.html
{% comment %}
<h1>{{question.question_text}}</h1>
<h2>vivo esta el la id {{question.id}}</h2>
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }}</li>
  {% endfor %}
</ul>
{% endcomment %}

<form
  action="{%url 'polls:vote' question.id%}"
  method="post"
>
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>{{question.question_text}}</h1>
    </legend>

    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %} {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{forloop.counter}}"
      value="{{choice.id}}"
    />
    <label for="choice{{forloop.counter}}"> {{choice.choice_text}} </label>
    {% endfor %}
  </fieldset>
  <input
    type="submit"
    value="Votar"
  />
</form>

platzipremiosapp/polls/templates/polls/index.html
{% if lastest_questions_list %}
<ul>
  {% for question in lastest_questions_list %}
  <li>
    <a href=" {%url 'polls:details' question.id %} ">
      {{question.question_text}}
    </a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No tenemos encuentas</p>
{% endif %}

platzipremiosapp/polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
  </li>
  {% endfor %}
</ul>
<a href="{% url 'polls:index' %}">Volver</a>